/* Net TP2_2022_IOPT_TOOLS - IOPT */
/* Automatic code generated by IOPT2C XSLT transformation. */


#include <string.h>
#include <stdlib.h>
#include "net_types.h"


#if defined(HTTP_SERVER) || defined(DBG_INFO)

static iopt_param_info TP2_2022_IOPT_TOOLS_input_info[] = {
    { "is_Humidity_Soil", 0 },
    { "is_Humidity_Air", 0 },
    { "is_Override_Irrigation", 0 },
    { "is_Meteo_Station_Rain", 0 },
    { NULL, 0 }
};

static iopt_param_info TP2_2022_IOPT_TOOLS_output_info[] = {
    { "os_Irrigation", 0 },
    { "os_Irrigation_Duration", 0 },
    { "os_Sensor_Check", 0 },
    { NULL, 0 }
};

static iopt_param_info TP2_2022_IOPT_TOOLS_marking_info[] = {
    { "p_2", 0 },
    { "p_7", 0 },
    { "p_12", 0 },
    { "p_23", 0 },
    { "p_56", 0 },
    { "p_80", 0 },
    { NULL, 0 }
};

static iopt_param_info TP2_2022_IOPT_TOOLS_tfired_info[] = {
    { "t_3", 0 },
    { "t_13", 0 },
    { "t_20", 0 },
    { "t_59", 0 },
    { "t_62", 0 },
    { "t_78", 0 },
    { "t_79", 0 },
    { "t_81", 0 },
    { "t_85", 0 },
    { "t_89", 0 },
    { "t_103", 0 },
    { "t_112", 0 },
    { NULL, 0 }
};

iopt_param_info* get_TP2_2022_IOPT_TOOLS_InputInfo()
{
    TP2_2022_IOPT_TOOLS_InputSignals* inputs = get_TP2_2022_IOPT_TOOLS_InputSignals();
    TP2_2022_IOPT_TOOLS_input_info[0].value = inputs->is_Humidity_Soil;
    TP2_2022_IOPT_TOOLS_input_info[1].value = inputs->is_Humidity_Air;
    TP2_2022_IOPT_TOOLS_input_info[2].value = inputs->is_Override_Irrigation;
    TP2_2022_IOPT_TOOLS_input_info[3].value = inputs->is_Meteo_Station_Rain;
    return TP2_2022_IOPT_TOOLS_input_info;
}

iopt_param_info* get_TP2_2022_IOPT_TOOLS_OutputInfo()
{
    TP2_2022_IOPT_TOOLS_PlaceOutputSignals* place_out = get_TP2_2022_IOPT_TOOLS_PlaceOutputSignals();
    TP2_2022_IOPT_TOOLS_EventOutputSignals* ev_out = get_TP2_2022_IOPT_TOOLS_EventOutputSignals();
    TP2_2022_IOPT_TOOLS_output_info[0].value = ev_out->os_Irrigation;
    TP2_2022_IOPT_TOOLS_output_info[1].value = place_out->os_Irrigation_Duration;
    TP2_2022_IOPT_TOOLS_output_info[2].value = place_out->os_Sensor_Check;
    return TP2_2022_IOPT_TOOLS_output_info;
}

iopt_param_info* get_TP2_2022_IOPT_TOOLS_MarkingInfo()
{
    TP2_2022_IOPT_TOOLS_NetMarking* marking = get_TP2_2022_IOPT_TOOLS_NetMarking();
    TP2_2022_IOPT_TOOLS_marking_info[0].value = marking->p_2;
    TP2_2022_IOPT_TOOLS_marking_info[1].value = marking->p_7;
    TP2_2022_IOPT_TOOLS_marking_info[2].value = marking->p_12;
    TP2_2022_IOPT_TOOLS_marking_info[3].value = marking->p_23;
    TP2_2022_IOPT_TOOLS_marking_info[4].value = marking->p_56;
    TP2_2022_IOPT_TOOLS_marking_info[5].value = marking->p_80;
    return TP2_2022_IOPT_TOOLS_marking_info;
}

void force_TP2_2022_IOPT_TOOLS_Inputs( iopt_param_info fv[],
        TP2_2022_IOPT_TOOLS_InputSignals* in )
{
    int i;
    for( i = 0; fv[i].name != NULL; ++i ) {
        if( strcmp( fv[i].name, TP2_2022_IOPT_TOOLS_input_info[0].name ) == 0 )
           in->is_Humidity_Soil = fv[i].value;
        else if( strcmp( fv[i].name, TP2_2022_IOPT_TOOLS_input_info[1].name ) == 0 )
           in->is_Humidity_Air = fv[i].value;
        else if( strcmp( fv[i].name, TP2_2022_IOPT_TOOLS_input_info[2].name ) == 0 )
           in->is_Override_Irrigation = fv[i].value;
        else if( strcmp( fv[i].name, TP2_2022_IOPT_TOOLS_input_info[3].name ) == 0 )
           in->is_Meteo_Station_Rain = fv[i].value;
    }
}

void force_TP2_2022_IOPT_TOOLS_Outputs( iopt_param_info fv[],
        TP2_2022_IOPT_TOOLS_PlaceOutputSignals* place_out,
        TP2_2022_IOPT_TOOLS_EventOutputSignals* ev_out )
{
    int i;
    for( i = 0; fv[i].name != NULL; ++i ) {
        if( strcmp( fv[i].name, TP2_2022_IOPT_TOOLS_output_info[0].name ) == 0 )
           ev_out->os_Irrigation = fv[i].value;
        else if( strcmp( fv[i].name, TP2_2022_IOPT_TOOLS_output_info[1].name ) == 0 )
           place_out->os_Irrigation_Duration = fv[i].value;
        else if( strcmp( fv[i].name, TP2_2022_IOPT_TOOLS_output_info[2].name ) == 0 )
           place_out->os_Sensor_Check = fv[i].value;
    }
}

void force_TP2_2022_IOPT_TOOLS_Marking( iopt_param_info fv[],
        TP2_2022_IOPT_TOOLS_NetMarking* m )
{
    int i;
    for( i = 0; fv[i].name != NULL; ++i ) {
        if( strcmp( fv[i].name, TP2_2022_IOPT_TOOLS_marking_info[0].name ) == 0 )
           m->p_2 = fv[i].value;
        else if( strcmp( fv[i].name, TP2_2022_IOPT_TOOLS_marking_info[1].name ) == 0 )
           m->p_7 = fv[i].value;
        else if( strcmp( fv[i].name, TP2_2022_IOPT_TOOLS_marking_info[2].name ) == 0 )
           m->p_12 = fv[i].value;
        else if( strcmp( fv[i].name, TP2_2022_IOPT_TOOLS_marking_info[3].name ) == 0 )
           m->p_23 = fv[i].value;
        else if( strcmp( fv[i].name, TP2_2022_IOPT_TOOLS_marking_info[4].name ) == 0 )
           m->p_56 = fv[i].value;
        else if( strcmp( fv[i].name, TP2_2022_IOPT_TOOLS_marking_info[5].name ) == 0 )
           m->p_80 = fv[i].value;
    }
}

iopt_param_info* get_TP2_2022_IOPT_TOOLS_TFiredInfo()
{
    TP2_2022_IOPT_TOOLS_TransitionFiring* tfired = get_TP2_2022_IOPT_TOOLS_TransitionFiring();
    TP2_2022_IOPT_TOOLS_tfired_info[0].value = tfired->t_3;
    TP2_2022_IOPT_TOOLS_tfired_info[1].value = tfired->t_13;
    TP2_2022_IOPT_TOOLS_tfired_info[2].value = tfired->t_20;
    TP2_2022_IOPT_TOOLS_tfired_info[3].value = tfired->t_59;
    TP2_2022_IOPT_TOOLS_tfired_info[4].value = tfired->t_62;
    TP2_2022_IOPT_TOOLS_tfired_info[5].value = tfired->t_78;
    TP2_2022_IOPT_TOOLS_tfired_info[6].value = tfired->t_79;
    TP2_2022_IOPT_TOOLS_tfired_info[7].value = tfired->t_81;
    TP2_2022_IOPT_TOOLS_tfired_info[8].value = tfired->t_85;
    TP2_2022_IOPT_TOOLS_tfired_info[9].value = tfired->t_89;
    TP2_2022_IOPT_TOOLS_tfired_info[10].value = tfired->t_103;
    TP2_2022_IOPT_TOOLS_tfired_info[11].value = tfired->t_112;
    return TP2_2022_IOPT_TOOLS_tfired_info;
}

#endif
